import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import SignOutButton from '@/components/auth/sign-out-button';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={inter.className}>
      <SignOutButton />
      {children}
    </body>
  </html>
);

export default RootLayout;
