name: Deploy Supabase Migrations to Production

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Backup roles
        run: supabase db dump --db-url "$SUPABASE_DB_URL" -f roles.sql --role-only
      - name: Backup schema
        run: supabase db dump --db-url "$SUPABASE_DB_URL" -f schema.sql
      - name: Backup data
        run: supabase db dump --db-url "$SUPABASE_DB_URL" -f data.sql --data-only --use-copy\

      - name: Move backups to new folder
        run: mkdir ./backups && mkdir ./backups/$(date +%Y%m%d_%H%M%S) && mv ./roles.sql ./backups/* && mv ./schema.sql ./backups/* && mv ./data.sql ./backups/*

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        with:
          source-directory: 'backups'
          destination-github-username: 'fastyform'
          destination-repository-name: 'backups'
          target-branch: main


      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push
